# _____           _                   ______                      _       
#/  __ \         | |                  | ___ \                    | |      
#| /  \/_   _ ___| |_ ___  _ __ ___   | |_/ /___ _ __   ___  _ __| |_ ___ 
#| |   | | | / __| __/ _ \| '_ ` _ \  |    // _ \ '_ \ / _ \| '__| __/ __|
#| \__/\ |_| \__ \ || (_) | | | | | | | |\ \  __/ |_) | (_) | |  | |_\__ \
# \____/\__,_|___/\__\___/|_| |_| |_| \_| \_\___| .__/ \___/|_|   \__|___/
#                                               | |                       
#                                               |_|            by Sanhak from Venix Coding


# to get support or suggest plugin to make join our discord server ! [come to get more free plugins]
Venix-Coding: "discord.gg/VQGdE9jpKK" 


Reasons-List:
  - "BadName"
  - "Toxic"
  - "fly"
  - "spam"
